name: Windows Build and Publish

on:
  push:
    branches:
      - wpf

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .\SADXModLoader.sln

jobs:
  build:
    name: ${{matrix.configuration}}
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Release]

    steps:
    - uses: actions/checkout@v3.3.0

    - name: Add Git hash to resources
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: echo ${{github.sha}} > ModManagerWPF/Resources/Version.txt

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.x' # Use a valid .NET SDK version here

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{matrix.configuration}} ${{env.SOLUTION_FILE_PATH}}

    - name: Publish WPF application
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: dotnet publish -c ${{matrix.configuration}} -r win-x64 --self-contained true --output publish

    - uses: actions/upload-artifact@v3.1.2
      with:
        name: ModManagerWPF-${{matrix.configuration}}
        path: ${{github.workspace}}/publish
