name: Windows Build and Publish

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  # Path to the WPF project file relative to the root of the project.
  WPF_PROJECT_FILE: ./ModManagerWPF/SAModManager.csproj

jobs:
  build:
    name: ${{matrix.configuration}}
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Release]

    steps:
    - uses: actions/checkout@v3.3.0

    - name: Add Git hash to resources
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: echo ${{github.sha}} > ModManagerWPF/Resources/Version.txt

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x' # Use a valid .NET SDK version here

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: dotnet restore ${{env.WPF_PROJECT_FILE}}

    - name: Publish 64-bit WPF application
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: dotnet publish -p:PublishSingleFile=true -r win-x64 -c Release --self-contained false

    - name: CleanUp Misc Files (64-bit)
      working-directory: ${{github.workspace}}\bin\Release\net7.0-windows\win-x64\publish
      run: del SAModManager.dll.config, SAModManager.pdb

    - name: Publish 32-bit WPF application
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: dotnet publish -p:PublishSingleFile=true -r win-x86 -c Release --self-contained false
      
    - name: CleanUp Misc Files (32-bit)
      working-directory: ${{github.workspace}}\bin\Release\net7.0-windows\win-x86\publish
      run: del SAModManager.dll.config, SAModManager.pdb
      
    - name: Create Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: |
         SA-Mod-Manager/bin/Release/net7.0-windows/win-x64/publish/*
         SA-Mod-Manager/bin/Release/net7.0-windows/win-x86/publish/*
        token: ${{ secrets.GITHUB_TOKEN }}
