name: Windows Build and Publish

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  # Path to the WPF project file relative to the root of the project.
  WPF_PROJECT_FILE: ./SA-Mod-Manager/SAModManager.csproj

jobs:
  build:
    name: ${{matrix.configuration}}
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Release]

    steps:
    - uses: actions/checkout@v3.3.0

    - name: Add Git hash to resources
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: echo ${{github.sha}} > SA-Mod-Manager/Resources/Version.txt

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0' 

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: dotnet restore ${{env.WPF_PROJECT_FILE}}

    - name: Publish 64-bit WPF application
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: dotnet publish -p:PublishSingleFile=true -r win-x64 -c Release --self-contained false
      
    - name: Create Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: |
         bin/Release/net7.0-windows/win-x64/publish/*
        token: ${{ secrets.GITHUB_TOKEN }}
